/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-05-29 17:14:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class studentdelete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("  <title>Delete Student</title>\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("      background: linear-gradient(to right, #fff5f8, #e0f7fa);\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      padding: 50px 20px;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("      color: #ff6f91;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    form {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      padding: 30px 40px;\r\n");
      out.write("      border-radius: 12px;\r\n");
      out.write("      box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      max-width: 400px;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    label {\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      display: block;\r\n");
      out.write("      margin-bottom: 8px;\r\n");
      out.write("      font-size: 1.1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"number\"] {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      font-size: 1rem;\r\n");
      out.write("      border-radius: 6px;\r\n");
      out.write("      border: 1px solid #ccc;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      transition: border-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"number\"]:focus {\r\n");
      out.write("      border-color: #4a90e2;\r\n");
      out.write("      outline: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"submit\"] {\r\n");
      out.write("      background-color: #ff6f91;\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      border: none;\r\n");
      out.write("      padding: 12px;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      border-radius: 6px;\r\n");
      out.write("      font-size: 1.1rem;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"submit\"]:hover {\r\n");
      out.write("      background-color: #e15578;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-top: 20px;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: #4a90e2;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      font-size: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a:hover {\r\n");
      out.write("      text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Message styling */\r\n");
      out.write("    .message {\r\n");
      out.write("      max-width: 400px;\r\n");
      out.write("      padding: 15px 20px;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .success-message {\r\n");
      out.write("      background-color: #d4edda;\r\n");
      out.write("      border: 1px solid #c3e6cb;\r\n");
      out.write("      color: #155724;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .error-message {\r\n");
      out.write("      background-color: #f8d7da;\r\n");
      out.write("      border: 1px solid #f5c6cb;\r\n");
      out.write("      color: #721c24;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <h2>🗑️ Delete Student</h2>\r\n");
      out.write("\r\n");
      out.write("  ");

    String message = (String) request.getAttribute("message");
    if (message != null) {
      // Simple heuristic: if message contains "success", show green, else red
      String cssClass = message.toLowerCase().contains("success") ? "success-message" : "error-message";
  
      out.write("\r\n");
      out.write("    <div class=\"message ");
      out.print( cssClass );
      out.write('"');
      out.write('>');
      out.print( message );
      out.write("</div>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <form action=\"DeleteStudentServlet\" method=\"post\" novalidate>\r\n");
      out.write("    <label for=\"id\">Enter Student ID to Delete:</label>\r\n");
      out.write("    <input type=\"number\" id=\"id\" name=\"id\" min=\"1\" required aria-required=\"true\" />\r\n");
      out.write("    <input type=\"submit\" value=\"Delete Student\" />\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("  <a href=\"index.jsp\">⬅️ Back to Home</a>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
